- name: run zookeeper container
  docker_container:
    name: zookeeper
    image: "{{ zookeeper_image }}"
    state: started
    detach: True
    network_mode: "host"
    env:
      MYID: "{{ zookeeper_id }}"
      SERVERS: "{{ zookeeper_servers_list }}"
    restart_policy: always
  tags:
    - zookeeper

